apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xo78y15um-dotnet-basic
  janus-idp.io/tekton: xo78y15um-dotnet-basic
  backstage.io/kubernetes-id: xo78y15um-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xo78y15um-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
